sudo: false

language: node_js
node_js:
  - 12

branches:
  only:
    - master

install:
  - npm install

cache:
  directories:
    - node_modules

dist: trusty

deploy:
  provider: heroku
  app: "boomber"
  api_key:
    secure: "63e88958-277a-4552-bc20-24bab81e97cc"